### PR TITLE
tests: Enable travis CI.

### PR DESCRIPTION
**Pull request by yaoyuannnn**
This enables Travis CI, which currently builds SMAUG and runs all the tests.

### CODE REVIEW

**Comment by yaoyuannnn** [comment]
@xyzsam Do you know how to run CI automatically for PR?

**Comment by xyzsam** [comment]
I had to initialize the Travis CI project for this repo. It's active now. I kicked off a build to get things started. You may need to make a trivial change and repush to trigger the build.

**Comment by xyzsam** [comment]
What you can do is update the Travis CI badge in the README to this link: https://travis-ci.org/harvard-acc/smaug.svg?branch=master. That should get the process going.

**Comment by yaoyuannnn** [comment]
> What you can do is update the Travis CI badge in the README to this link: https://travis-ci.org/harvard-acc/smaug.svg?branch=master. That should get the process going.

Yes, added a commit for updating the Travis CI badge.

**Comment by xyzsam** [comment]
Going to rebase and merge to keep the experiments submodule commit separate.

**Pull request merged**
